name: installable

on:
  release:
    types: [created]

jobs:
  zip:
    name: Create and Attach Installable ZIP

    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Installable ZIP
        shell: cmd
        run: CreateInstallable.bat ${{ github.event.release.tag_name }}

      - name: Attach ZIP to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: Installable.zip
          asset_name: Schrankenwaerter.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
